# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# p10k config import
ZSH_THEME="powerlevel10k/powerlevel10k"

zstyle ':omz:update' mode auto      # update automatically without asking

source /usr/share/zsh-antigen/antigen.zsh
antigen use oh-my-zsh

antigen bundle aliases
antigen bundle git

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions

antigen theme romkatv/powerlevel10k

antigen apply

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(
#   aliases
#   git 
#   )
#
# source $ZSH/oh-my-zsh.sh
#
# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases

#config editing
alias sc="source ~/.zshrc"
alias ec="nvim ~/.zshrc"

#nvim alt config
alias nvim-kickstart='NVIM_APPNAME="nvim-kickstart" nvim'

#npm aliases
alias nrdb='npm run debug'
alias nrd='npm run dev'
alias ns='npm start'

#terminal aliases
alias ag='ag --path-to-ignore ~/.ignore'
alias lg='lazygit'
# alias man='batman'
alias tmuxa='tmux attach'
alias mux='tmuxinator'
alias ag='ag --path-to-ignore ~/.ignore'
alias bat='batcat'
alias batp='bat package.json'
alias batr='bat README.md'
# apt aliases
alias sai='sudo apt install'
alias sau='sudo apt update'
alias sa='sudo apt'

cdl() {cd "$1" && l}

# Configuration to load nvm - node version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# neovim 
export PATH="$HOME/neovim/bin:$PATH"
export EDITOR=nvim

fpath=(~/.zsh.d/ $fpath)


# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# initialize zoxide
eval "$(zoxide init zsh --cmd cd)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Vim keybinds for the terminal because I can't do Emac keybinds
set -o vi
